### ISSUE TITLE
Is it possible to use strict as some inspections?

### ISSUE THREAD

**Issue by dracodoc** [hadley/strict#11]
If the strict checks can be run as inspections instead of fail on error, there will be these advantages:
- Running inspections can gather all the errors in one run instead of one error at a time (assuming the original code can be executed normally), which provide a good overview and are more efficient. For example I have several cases needing fully qualified name, but I have to run the code again and again to find yet another case.
- This give user the option to selectively fix some issues. I knew this could be different with the motivating philosophy, though sometimes there are some special cases that don't have a perfect solution yet, like the multiple source of `%>%`.
- I would say all the conditions that `strict` check are not equal. Some definitely should be fixed, some are less serious. An inspection that report all the problems will allow user to apply some priority on them.

I understand to run these conditions check as inspections probably is not easy, and could need substantial changes from current code.

**Comment by hadley** [comment]
It sounds like you're looking for something more like a linting system, i.e. [lintr](https://github.com/jimhester/lintr)

**Comment by dracodoc** [comment]
Yes it will be similar to that, but checking different issues. I found the most checks in `lintr` are not really useful for me (a lot of them are formatting issues will not happen for me).

I knew this usage probably didn't follow the original **strict** philosophy, but after changed one place in `strict_abort` from `abort(msg)` to `warn(msg)`, I can run my Shiny app with `strict` now and see all the issues in one run. There are some duplicates can be filtered out, but it's still much easier for me. Otherwise I need to fix every issue in order to see next issue.

```r
> shiny::runApp('shiny/app')
Loading required package: shiny
Loading required package: pacman

Listening on http://127.0.0.1:4858
Warning: [strict]
Multiple definitions found for `box`.
Please pick one:
 * shinydashboard::box
 * graphics::box
Warning: [strict]
Multiple definitions found for `box`.
Please pick one:
 * shinydashboard::box
 * graphics::box
Warning: [strict]
Multiple definitions found for `source`.
Please pick one:
 * XML::source
 * base::source
```
