### ISSUE TITLE
Force local environment for variables inside functions

### ISSUE THREAD

**Issue by juuussi** [hadley/strict#17]
Would be great to have an error when trying to access variables outside of the local scope from inside a function, unless explicitly specified. I personally think this is one of the most useful checks in Perl strict, and something that causes a lot of problems for especially beginner R coders.

**Comment by hadley** [comment]
Unfortunately there's no practical way to do that. Take this simple function:

```R
f <- function(x, y) {
  x + y
}
```

It accesses two variables from outside the local scope: `{` and `+`.
