### ISSUE TITLE
Function from another package throws a warning

### ISSUE THREAD

**Issue by privefl** [hadley/strict#18]
If I use the `sobel` function from the package **multilevel**:
```
library(multilevel)
library(strict)
data(bh1996)
sobel(pred=bh1996$HRS,med=bh1996$LEAD,out=bh1996$WBEING)
```
I get 
```
Warning messages:
1: In summary(model1)$coef : partial match of 'coef' to 'coefficients'
2: In summary(model2)$coef : partial match of 'coef' to 'coefficients'
3: In summary(model3)$coef : partial match of 'coef' to 'coefficients'
```

Moreover, using `lax` around it doesn't make the warnings go away.

**Comment by hadley** [comment]
Unfortunately the partial matching warnings are global options managed by R so I can't make them only affect local code. But I can make `lax()` do the right thing.
