### ISSUE TITLE
Should there be a warning mode?

### ISSUE THREAD

**Issue by dracodoc** [hadley/strict#6]
I think sometimes giving a warning instead of just fail have advantages. Like there are some code not in you control, error can prevent it to run but you cannot fix it.

Warning cannot force user to fix the problem, but it can still tell careful users about the problem. With warnings I can apply `strict` to all my code and have a peace of mind that many things will be checked, but if a lot of things will break immediately I'll hesitate to add it.

**Comment by hadley** [comment]
That's not the philosophy of strict — the whole point is to break things immediately so that you're forced to fix them.  If you sit down and switch to `library(strict)` I don't think it's going to take you look to fix all the problems.

**Comment by dracodoc** [comment]
I didn't realize `strict` will not have effect on existing packages. So the point of "prevent some code to run but you cannot fix it" doesn't exist.
