### ISSUE TITLE
Is there a better option than use fully qualified name in every case?

### ISSUE THREAD

**Issue by dracodoc** [hadley/strict#7]
I tried `strict` with my Shiny app, the first error is this:

```r
Multiple definitions found for `box`.
Please pick one:
 * shinydashboard::box
 * graphics::box
```

Obvious solution is to use the fully qualified name. However this can be a little cumbersome, another side effect is my Shiny UI code indented a lot, using long names may force me to add more line breaks to keep code within 80 columns.

In Python we can use `import x as y`. With R we can actually just use `sbox <- shinydashboard::box` and use `sbox` everywhere.

I'm wondering if this is a good solution.

**Comment by hadley** [comment]
The goal of strict is to bring these problems to light, not to solve. But I think using `box <- shinydashboard::box` is a fine solution.
